name: release
on:
    release:
        types: [created]

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v4
            - name: setup-jdk
              uses: actions/setup-java@v4
              with:
                  distribution: 'temurin'
                  java-version: '17' 
                  cache: sbt          
            - name: publish
              uses: sbt/setup-sbt@v1
            - run: sbt ci-release
              env:
                RELEASE_VERSION: ${{ github.ref_name }}
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
                SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
                SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
                PGP_SECRET: ${{ secrets.PGP_SECRET }}
                PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}